apiVersion: apps/v1
kind: Deployment
metadata:
  name: ceph-cache-dropper
  namespace: openshift-storage
  labels:
    app: ceph-cache-dropper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ceph-cache-dropper
  template:
    metadata:
      labels:
        app: ceph-cache-dropper
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: ceph-cache-dropper
        image: quay.io/bengland2/ceph_cache_drop:debug
        imagePullPolicy: Always
        ports:
        - containerPort: 9432
        command: ["/usr/bin/python"]
        args: ["/opt/ceph_cache_drop/osd-cache-drop-websvc.py"]
        imagePullPolicy: Always
        env:
          - name: ROOK_ADMIN_SECRET
            valueFrom:
              secretKeyRef:
                name: rook-ceph-mon
                key: admin-secret
        securityContext:
          privileged: true
        # we don't need all the same volumes as the toolbox pod
        volumeMounts:
          - name: mon-endpoint-volume
            mountPath: /etc/rook
          - mountPath: /sys/bus
            name: sysbus
          - mountPath: /lib/modules
            name: libmodules
      volumes:
        - name: mon-endpoint-volume
          configMap:
            name: rook-ceph-mon-endpoints
            items:
            - key: data
              path: mon-endpoints
        - name: dev
          hostPath:
            path: /dev
        - name: sysbus
          hostPath:
            path: /sys/bus
        - name: libmodules
          hostPath:
            path: /lib/modules
